server:
  port: 8081

spring:
  application:
    name: sentinelflow
  
  datasource:
    url: jdbc:h2:file:./data/sentinelflow;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  service:
    url: http://localhost:8000

jwt:
  secret: 40b7d388-1355-4910-8874-e3db7521f8fde993fc02-dac2-4294-82d3-bbcc7f594dbe
  expiration: 86400000